
import  java.awt.event.ActionListener;
import  java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import  java.sql.*;
import  java.sql.PreparedStatement;
import java .util.ArrayList;
import  java.util.logging.Level;     
import  java.util.logging.Logger;    
import  javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class calculatePay extends javax.swing.JFrame implements ActionListener,MouseListener {

 MainClass main = new MainClass();   

    public calculatePay() {
        initComponents();
        
     showEmployeeFromTable();
     double pay = 50;
     double ftax =0.0126;
     double gpay = 0.0726;
     double opay = 35 ;
     double npay =  0.10     ;
     double sstax  = 0.05    ;
             
     gp.setText("7.26%");
     ft.setText("1.2%");
     otp.setText("35 php");
     np.setText  ("10%");      
     sst.setText  ("5%");      
     payField.setText("0");        
        
    }

    
    
    
    
    
     public ArrayList<EmployeeInfo> getEmployeeList(){
     
      
      ArrayList<EmployeeInfo> employeeList = new ArrayList<EmployeeInfo>();
      Connection Conn = main.getConnection();
      String sql ="Select * from employeedata";
      Statement stmt;
      ResultSet rs;
      
      try{
          stmt = Conn.createStatement();
          rs = stmt.executeQuery(sql);
          EmployeeInfo employeeinfo;
          
          while (rs.next()){
              
              employeeinfo = new EmployeeInfo(Integer.parseInt(rs.getString("id")), rs.getString("employeename"), rs.getString("gender"), rs.getString("address"), Double.parseDouble(rs.getString("balance")),rs.getString("employeeposition"));
              employeeList.add(employeeinfo);
          }
          }
      catch(SQLException e){
      
      Logger.getLogger(CheckDelete.class.getName()).log(Level.SEVERE,null,e);
      }
      return employeeList;
  
  }
     
     public void showEmployeeFromTable(){
   ArrayList<EmployeeInfo> list = getEmployeeList();
   DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
   
   model.setRowCount(0);
   Object[] row = new Object[2];
   for (int x = 0 ; x<list.size(); x++){
   
   row[0] = list.get(x).getid();
   row[1] = list.get(x).getemployeeName();
    
   model.addRow(row) ;
   }
     }
     
    
    
    public void  ShowItem(int index){
   
   yourName.setText(Integer.toString(getEmployeeList().get(index).getid())); 
   yourBalance.setText(Double.toString(getEmployeeList().get(index).getBalance())); 
    
    
    
    
    
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        daysWorked = new javax.swing.JTextField();
        payField = new javax.swing.JTextField();
        yourBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yourName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gp = new javax.swing.JTextField();
        np = new javax.swing.JTextField();
        ft = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        sst = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 430, 60);

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NAME"
            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 430, 180);

        daysWorked.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        daysWorked.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        daysWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysWorkedActionPerformed(evt);
            }
        });
        jPanel1.add(daysWorked);
        daysWorked.setBounds(170, 400, 250, 30);

        payField.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        payField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFieldActionPerformed(evt);
            }
        });
        jPanel1.add(payField);
        payField.setBounds(280, 590, 120, 30);

        yourBalance.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        yourBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yourBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(yourBalance);
        yourBalance.setBounds(170, 360, 250, 30);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NO. OF HRS WORKED:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 400, 170, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CALCULATE YOUR PAY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 80, 200, 23);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SOCIAL SECURITY TAX");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 460, 130, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("YOUR BALANCE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 360, 170, 30);

        yourName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        yourName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yourName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourNameActionPerformed(evt);
            }
        });
        jPanel1.add(yourName);
        yourName.setBounds(170, 320, 250, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PAY:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 590, 50, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GROSS PAY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 460, 100, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NET PAY");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 510, 100, 30);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("FEDERAL TAXES");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 560, 100, 30);

        gp.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        gp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpActionPerformed(evt);
            }
        });
        jPanel1.add(gp);
        gp.setBounds(120, 460, 110, 30);

        np.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        np.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        jPanel1.add(np);
        np.setBounds(120, 510, 110, 30);

        ft.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftActionPerformed(evt);
            }
        });
        jPanel1.add(ft);
        ft.setBounds(120, 560, 110, 30);

        back.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(290, 630, 100, 23);

        calculate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        calculate.setText("CALCULATE");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel1.add(calculate);
        calculate.setBounds(280, 540, 100, 23);

        sst.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        sst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstActionPerformed(evt);
            }
        });
        jPanel1.add(sst);
        sst.setBounds(280, 490, 110, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("YOUR NAME:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 320, 150, 30);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Over Time Pay");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 620, 100, 30);

        otp.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        otp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });
        jPanel1.add(otp);
        otp.setBounds(120, 620, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daysWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysWorkedActionPerformed

    private void payFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payFieldActionPerformed

    private void yourBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourBalanceActionPerformed

    private void yourNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourNameActionPerformed

    private void gpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void ftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      this.dispose();
      new eLoginSuccessfully().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void sstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstActionPerformed

    private void otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
      int index = employeeTable.getSelectedRow();
      ShowItem(index);
    }//GEN-LAST:event_employeeTableMouseClicked

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       String command = evt.getActionCommand();
       double p = 40;
       double ft = .12;      
       double gp = .0726;
       double dw = 0;
       double otp= 35;
       double np= .10;
       double sst= .5;
       String textFieldValue = daysWorked.getText();
       int val = Integer.parseInt(daysWorked.getText());
       
       
       if (val <=8 || val>0){} 
       
       
       double pay = val * p;
       double tDeduct = ft + sst;
       double overtime = gp + np;
       
       double ded = tDeduct * val;
       double add = overtime *val ;
       
       
       double addedPay = pay + add;
       double finalPay = addedPay - ded;
       double fPayXot = (val*p)+ otp - ded;
       
       for (double x =9 ; x<100; x++){
      double k = otp *x; 
       
       }
       if (val<=8){
       payField.setText("" + finalPay);
           System.out.println("no OT");
       }else if(val >=9){
       payField.setText(""+fPayXot);
           System.out.println("OVERTIME");
 
       }
               
       
       
       
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatePay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField daysWorked;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField ft;
    private javax.swing.JTextField gp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField np;
    private javax.swing.JTextField otp;
    private javax.swing.JTextField payField;
    private javax.swing.JTextField sst;
    private javax.swing.JTextField yourBalance;
    private javax.swing.JTextField yourName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
