
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class EmployeeSignUp extends javax.swing.JFrame implements ActionListener {
    MainClass main = new MainClass();
    /**
     * Creates new form EmployeeSignUp
     */
    public EmployeeSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newEmployeePosition = new javax.swing.JTextField();
        newEmployeeName = new javax.swing.JTextField();
        newEmployeeUser = new javax.swing.JTextField();
        newEmployeeGender = new javax.swing.JTextField();
        newEmployeeAddress = new javax.swing.JTextField();
        newEmployeeBalance = new javax.swing.JTextField();
        newUserID = new javax.swing.JTextField();
        newEmployeePinCode = new javax.swing.JTextField();
        createEmployeeAccount = new javax.swing.JButton();
        adminSignUpBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("BALANCE:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 380, 70, 30);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employeee-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 80));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 340, 80);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("SIGN UP FOR EMPLOYEE ACCOUNT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 100, 230, 19);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 30, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USERNAME :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 219, 90, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("     POSITION :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 420, 110, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("GENDER :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 299, 90, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 340, 70, 30);

        newEmployeePosition.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeePosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeePosition);
        newEmployeePosition.setBounds(130, 420, 170, 30);

        newEmployeeName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeeName);
        newEmployeeName.setBounds(130, 180, 170, 30);

        newEmployeeUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeeUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeeUser);
        newEmployeeUser.setBounds(130, 220, 170, 30);

        newEmployeeGender.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeeGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeeGender);
        newEmployeeGender.setBounds(130, 300, 170, 30);

        newEmployeeAddress.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeeAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeeAddress);
        newEmployeeAddress.setBounds(130, 340, 170, 30);

        newEmployeeBalance.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeeBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeeBalance);
        newEmployeeBalance.setBounds(130, 380, 170, 30);

        newUserID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newUserID);
        newUserID.setBounds(130, 140, 170, 30);

        newEmployeePinCode.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        newEmployeePinCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(newEmployeePinCode);
        newEmployeePinCode.setBounds(130, 260, 170, 30);

        createEmployeeAccount.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        createEmployeeAccount.setText("CREATE ACCOUNT");
        createEmployeeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeAccountActionPerformed(evt);
            }
        });
        jPanel1.add(createEmployeeAccount);
        createEmployeeAccount.setBounds(160, 470, 140, 23);

        adminSignUpBack.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        adminSignUpBack.setText("BACK");
        adminSignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSignUpBackActionPerformed(evt);
            }
        });
        jPanel1.add(adminSignUpBack);
        adminSignUpBack.setBounds(40, 470, 72, 23);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("EMPLOYEE NAME :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 180, 130, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("PINCODE :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 259, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminSignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSignUpBackActionPerformed
         pickFrame pf = new pickFrame();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminSignUpBackActionPerformed

    private void createEmployeeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeAccountActionPerformed
      try{
        if (  newUserID.getText().equals("")
            || newEmployeeName.getText(). equals("")
            || newEmployeeUser.getText(). equals("")
            || newEmployeePinCode.getText().equals("")
            || newEmployeeGender.getText().equals("")
            || newEmployeeAddress.getText().equals("")
            || newEmployeeBalance.getText().equals("") 
            || newEmployeePosition.getText().equals(""))
            
            {
             JOptionPane.showMessageDialog(null,"Please fill up the form before proceeding Thank you!!!");
            Connection conn = main.getConnection();
            Statement stmt = conn.createStatement();
            
            
            
            } else if (newEmployeePinCode.getText().equals(newEmployeePinCode.getText())){
                   
                
                
                
            
            Connection conn = main.getConnection();
            Statement stmt = conn.createStatement(); 
                    
        String id = newUserID.getText();   
        
        
        String name  = newEmployeeName.getText();
        String uName  = newEmployeeUser.getText();
        String pin  = newEmployeePinCode.getText(); 
        String gender   = newEmployeeGender.getText();
        String address  = newEmployeeAddress.getText();       
        String bal  = newEmployeeBalance.getText();     
        String pos =  newEmployeePosition.getText();            
                    
        String sql = 
              "INSERT INTO employeedata (id, employeename, username, pincode, gender, address, balance, employeeposition) "
                + "VALUES ('"+ id +"','"+ name +"','"+ uName+ "','"+ pin +"','"+ gender +"','"+ address +"','"+ bal + "','"+ pos+"')";

        
                JOptionPane.showMessageDialog(null,"CREATING NEW ACCOUNT PLEASE WAIT...");
                stmt.executeUpdate(sql);    
                 JOptionPane.showMessageDialog(null,"ACCOUNT CREATED SUCCESSFULLY.");
                 dispose();
                 new EmployeeLogin().setVisible(true);
                 
                    
                    }
         }
      catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex.getMessage());

     }
        
        
        
        
    }//GEN-LAST:event_createEmployeeAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminSignUpBack;
    private javax.swing.JButton createEmployeeAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newEmployeeAddress;
    private javax.swing.JTextField newEmployeeBalance;
    private javax.swing.JTextField newEmployeeGender;
    private javax.swing.JTextField newEmployeeName;
    private javax.swing.JTextField newEmployeePinCode;
    private javax.swing.JTextField newEmployeePosition;
    private javax.swing.JTextField newEmployeeUser;
    private javax.swing.JTextField newUserID;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
